// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFiles(arg1:Array<string>):Promise<Array<string>>;

export function CharacterLimit(arg1:string,arg2:number):Promise<void>;

export function CheckForUpdates():Promise<main.VersionInfo>;

export function ClearFiles():Promise<Array<string>>;

export function Compress(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number):Promise<void>;

export function ConformityLimit(arg1:string,arg2:number):Promise<void>;

export function Gain(arg1:string,arg2:number):Promise<void>;

export function GetFiles():Promise<Array<string>>;

export function GetOS():Promise<string>;

export function GetOutputFolder():Promise<string>;

export function GetPlatformFormats():Promise<Array<string>>;

export function GetTelemetryEnabled():Promise<boolean>;

export function GetVersion():Promise<string>;

export function LUFS(arg1:string):Promise<number>;

export function LoadPreferences():Promise<main.Preferences>;

export function MetadataFields():Promise<Array<string>>;

export function PCMFileCoherence(arg1:string):Promise<number>;

export function PreviewSize(arg1:main.ProcessConfig):Promise<void>;

export function Process(arg1:main.ProcessConfig):Promise<void>;

export function ReadMetadata(arg1:string):Promise<Record<string, string>>;

export function RemoveFile(arg1:number):Promise<Array<string>>;

export function ResetPreferences():Promise<void>;

export function ResetTelemetryID():Promise<string>;

export function SavePreferences(arg1:main.Preferences):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<Array<string>>;

export function SendLogReport():Promise<void>;

export function SetInputFolder(arg1:string):Promise<string>;

export function SetOutputFolder():Promise<string>;

export function SetTelemetryEnabled(arg1:boolean):Promise<void>;

export function StartWatching():Promise<boolean>;

export function StopWatching():Promise<void>;

export function WriteMetadata(arg1:string,arg2:Record<string, string>):Promise<void>;
