// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['AudioNormalizer']['AddFiles'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['AudioNormalizer']['CheckForUpdates']();
}

export function ClearFiles() {
  return window['go']['main']['AudioNormalizer']['ClearFiles']();
}

export function GetFiles() {
  return window['go']['main']['AudioNormalizer']['GetFiles']();
}

export function GetOS() {
  return window['go']['main']['AudioNormalizer']['GetOS']();
}

export function GetOutputFolder() {
  return window['go']['main']['AudioNormalizer']['GetOutputFolder']();
}

export function GetPlatformFormats() {
  return window['go']['main']['AudioNormalizer']['GetPlatformFormats']();
}

export function GetTelemetryEnabled() {
  return window['go']['main']['AudioNormalizer']['GetTelemetryEnabled']();
}

export function GetVersion() {
  return window['go']['main']['AudioNormalizer']['GetVersion']();
}

export function LoadPreferences() {
  return window['go']['main']['AudioNormalizer']['LoadPreferences']();
}

export function MetadataFields() {
  return window['go']['main']['AudioNormalizer']['MetadataFields']();
}

export function PreviewSize(arg1) {
  return window['go']['main']['AudioNormalizer']['PreviewSize'](arg1);
}

export function Process(arg1) {
  return window['go']['main']['AudioNormalizer']['Process'](arg1);
}

export function ReadMetadata(arg1) {
  return window['go']['main']['AudioNormalizer']['ReadMetadata'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['main']['AudioNormalizer']['RemoveFile'](arg1);
}

export function ResetPreferences() {
  return window['go']['main']['AudioNormalizer']['ResetPreferences']();
}

export function ResetTelemetryID() {
  return window['go']['main']['AudioNormalizer']['ResetTelemetryID']();
}

export function SavePreferences(arg1) {
  return window['go']['main']['AudioNormalizer']['SavePreferences'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['AudioNormalizer']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['AudioNormalizer']['SelectFolder']();
}

export function SendLogReport() {
  return window['go']['main']['AudioNormalizer']['SendLogReport']();
}

export function SetInputFolder(arg1) {
  return window['go']['main']['AudioNormalizer']['SetInputFolder'](arg1);
}

export function SetOutputFolder() {
  return window['go']['main']['AudioNormalizer']['SetOutputFolder']();
}

export function SetTelemetryEnabled(arg1) {
  return window['go']['main']['AudioNormalizer']['SetTelemetryEnabled'](arg1);
}

export function StartWatching() {
  return window['go']['main']['AudioNormalizer']['StartWatching']();
}

export function StopWatching() {
  return window['go']['main']['AudioNormalizer']['StopWatching']();
}

export function WriteMetadata(arg1, arg2) {
  return window['go']['main']['AudioNormalizer']['WriteMetadata'](arg1, arg2);
}
