// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed resources/Brockmann-Regular.ttf
var resourceBrockmannRegularTtfData []byte
var resourceBrockmannRegularTtf = &fyne.StaticResource{
	StaticName:    "resources/Brockmann-Regular.ttf",
	StaticContent: resourceBrockmannRegularTtfData,
}

//go:embed resources/tntAppLogoForDark.png
var resourceTntAppLogoForDarkPngData []byte
var resourceTntAppLogoForDarkPng = &fyne.StaticResource{
	StaticName:    "resources/tntAppLogoForDark.png",
	StaticContent: resourceTntAppLogoForDarkPngData,
}

//go:embed resources/tntAppLogoForLight.png
var resourceTntAppLogoForLightPngData []byte
var resourceTntAppLogoForLightPng = &fyne.StaticResource{
	StaticName:    "resources/tntAppLogoForLight.png",
	StaticContent: resourceTntAppLogoForLightPngData,
}
