// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed buildBlocks/tntAppLogoForDark.png
var resourceTntAppLogoForDarkPngData []byte
var resourceTntAppLogoForDarkPng = &fyne.StaticResource{
	StaticName:    "buildBlocks/tntAppLogoForDark.png",
	StaticContent: resourceTntAppLogoForDarkPngData,
}

//go:embed buildBlocks/tntAppLogoForLight.png
var resourceTntAppLogoForLightPngData []byte
var resourceTntAppLogoForLightPng = &fyne.StaticResource{
	StaticName:    "buildBlocks/tntAppLogoForLight.png",
	StaticContent: resourceTntAppLogoForLightPngData,
}

//go:embed buildBlocks/Wotfard-Regular.ttf
var resourceWotfardRegularTtfData []byte
var resourceWotfardRegularTtf = &fyne.StaticResource{
	StaticName:    "buildBlocks/Wotfard-Regular.ttf",
	StaticContent: resourceWotfardRegularTtfData,
}
