name: Upload TNT JSON

on:
  push:
    branches: ["*"]
    paths:
      - 'Distribution/tnt-version.json'
  workflow_dispatch:

jobs:
  upload_tnt_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload to OVH
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OVH_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OVH_SECRET }}
        run: |
          aws s3 cp "Distribution/tnt-version.json" "s3://${{ secrets.OVH_BUCKET }}/" \
          --endpoint-url "${{ secrets.OVH_ENDPOINT }}" \
          --acl public-read
